// home
export const LISTS_REQUEST_POST = 'LISTS_REQUEST_POST';
export const LISTS_RECEIVE_POST = 'LISTS_RECEIVE_POST';
export const LISTS_FETCH_POST = 'LISTS_FETCH_POST';


// detail
export const DETAIL_REQUEST_POST = 'DETAIL_REQUEST_POST';
export const DETAIL_RECEIVE_POST = 'DETAIL_RECEIVE_POST';
export const DETAIL_FETCH_POST = 'DETAIL_FETCH_POST';
