// home
export const LISTS_REQUEST_POST = 'LISTS_REQUEST_POST';
export const LISTS_RECEIVE_POST = 'LISTS_RECEIVE_POST';
export const LISTS_FETCH_POST = 'LISTS_FETCH_POST';
export const LISTS_RECEIVE_MORE_POST = 'LISTS_RECEIVE_MORE_POST';


// detail
export const DETAIL_REQUEST_POST = 'DETAIL_REQUEST_POST';
export const DETAIL_RECEIVE_POST = 'DETAIL_RECEIVE_POST';
export const DETAIL_FETCH_POST = 'DETAIL_FETCH_POST';


// user
export const USER_REQUEST_POST = 'USER_REQUEST_POST';
export const USER_RECEIVE_POST = 'USER_RECEIVE_POST';
export const USER_FETCH_POST = 'USER_FETCH_POST';

// richeditor
export const RICH_EDITOR_STATE = 'RICH_EDITOR_STATE';


// Login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_OUT = 'LOGIN_OUT';


// post
export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_FAIL = 'POST_FAIL';


// comment
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS';
export const COMMENT_FAIL = 'COMMENT_FAIL';


// collect
export const COLLECT_SUCCESS = 'COLLECT_SUCCESS';
export const COLLECT_FAIL = 'COLLECT_FAIL';
export const UNCOLLECT_SUCCESS = 'UNCOLLECT_SUCCESS';
export const UNCOLLECT_FAIL = 'UNCOLLECT_FAIL';
export const USER_COLLECTTOPICS_SUCCESS = 'USER_COLLECTTOPICS_SUCCESS';
export const USER_COLLECTTOPICS_FAIL = 'USER_COLLECTTOPICS_FAIL';
export const DEFAULTSTATUS = 'DEFAULTSTATUS';
